# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem 'sinatra'
gem 'sinatra-namespace'
gem 'dotenv'
gem 'mysql2'
gem 'rspec'
gem 'puma'
gem 'builder'
gem 'haml', '>= 3.0'
gem 'simplecov', require: false